### ISSUE TITLE
WebGLFrameSink.stripe results in flipped, quarter-size image in Firefox

### ISSUE THREAD

**Issue by mart-jansink** [brion/yuv-canvas#37]
`WebGLFrameSink.stripe` is enabled by default since e8d262f08aeb17e20966d46aa06258dee40ba3cc. However, I'm now seeing a flipped, quarter-size image in only the bottom right corner:

<img width="1728" alt="Screenshot 2022-04-04 at 14 36 03" src="https://user-images.githubusercontent.com/4381258/161545884-85ca5a0d-af25-43c2-aeff-a8580bf88801.png">

This at least happens in the latest (nightly) version of Firefox on macOS Monterey running on an M1 MacBook Pro, not in Safari or Chrome. Setting `WebGLFrameSink.stripe = false` solves the problem, but of course disables the performance improvements as well.

**Comment by bvibber** [comment]
Urgh. I'll get on this.

**Comment by bvibber** [comment]
(Can confirm in Firefox on M1 MacBook Air)

**Comment by bvibber** [comment]
Bad news is I don't know what's actually wrong -- something's awry with the scaling on the texture when using the intermediate framebuffer, but I'm not sure why only Firefox on Mac gets it wrong. :(

Good news is I realized why the non-stripe code path was slow on some browsers in recent times: it was running texImage2d to upload new textures instead of texSubImage2d to update existing ones. So if all goes well in testing, I'll take that back out, use proper caching of textures for the non-stripe path, and be fixed. :D

**Comment by mart-jansink** [comment]
Thanks for the quick response! Weird that it really only happens with Firefox on M1 CPUs, but this solution is fine of course.

**Comment by bvibber** [comment]
Oh it wasn't just M1 -- it happened also on Intel and AMD GPUs on macOS 12.3 (only in Firefox).
